# Default values for hellomsa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  frontendapp:
    name: test
    image: 639785999924.dkr.ecr.ap-northeast-2.amazonaws.com/test_jojuhyeon
    tag: latest
    port: 3000
nginx:
  image: nginx
  tag: latest
