apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/jjh920/test_joju2.git
    path: path/to/kubernetes/manifests
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
