
ECR에서 최신 이미지를 가져와서 values.yaml 파일에 이미지 정보를 작성하는 방법은 일반적으로 자동화된 스크립트 또는 도구를 사용하여야 합니다. 이를 수행하기 위해서는 AWS CLI를 사용하여 ECR에 접근하고 최신 이미지의 태그를 가져와야 합니다. 그런 다음 이 정보를 사용하여 values.yaml 파일을 생성할 수 있습니다.

아래는 Python 스크립트를 사용하여 이 작업을 수행하는 예시입니다. 이 스크립트는 AWS CLI를 사용하여 ECR에서 최신 이미지의 태그를 가져옵니다.

python
Copy code
import subprocess
import yaml

# ECR 리포지토리 및 이미지 이름
repository = "639785999924.dkr.ecr.ap-northeast-2.amazonaws.com/test_jojuhyeon"

# AWS CLI를 사용하여 최신 이미지 태그 가져오기
command = f"aws ecr describe-images --repository-name {repository} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text"
latest_tag = subprocess.check_output(command, shell=True, encoding="utf-8").strip()

# values.yaml 파일에 이미지 정보 작성
values = {
    "replicaCount": 1,
    "services": {
        "frontendapp": {
            "name": "test",
            "image": f"{repository}:{latest_tag}",
            "tag": latest_tag,
            "port": 3000
        }
    }
}

# values.yaml 파일 저장
with open("values.yaml", "w") as f:
    yaml.dump(values, f)
