replicaCount: 1
imagePullSecrets:
  - name: ecr-regcred
nameOverride: ""
fullnameOverride: ""

image:
  repository: 639785999924.dkr.ecr.ap-northeast-2.amazonaws.com/test_jojuhyeon
  tag: latest
  port: 1111
